### ISSUE TITLE
NPE in console

### ISSUE THREAD

**Issue by downboy** [Vontus/MagicBottle#2]
[16:05:57 ERROR]: Could not pass event PrepareItemCraftEvent to MagicBottle v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar
:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:g
it-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar
:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar
:git-Spigot-de459a2-51263e9]
    at net.dzikoysk.wildskript.objects.recipe.ResultEvent.onInventoryClick(ResultEvent.java:49) 
[Wildskript-fix.jar:?]
    at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?
:1.8.0_121]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [server.jar:
git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:gi
t-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar
:git-Spigot-de459a2-51263e9]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar
:git-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1861) [server.jar:
git-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Sp
igot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Sp
igot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-
Spigot-de459a2-51263e9]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-de459a2
-51263e9]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [server.jar:git
-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git
-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git
-Spigot-de459a2-51263e9]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:g
it-Spigot-de459a2-51263e9]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
    at vontus.magicbottle.Events.onPrepareCraft(Events.java:52) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor441.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?
:1.8.0_121]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar
:git-Spigot-de459a2-51263e9]
    ... 23 more

**Comment by Vontus** [comment]
Hello. What were you trying to do when the exception appeared?

**Comment by downboy** [comment]
I'm trying to make the bottle. But every time I add a item to the craftingtable it's spams my console

**Comment by Vontus** [comment]
I'm not able to reproduce the exception, placing the items in a crafting table doesn't throw it for me; but I may have solved it in this commit b266850fc134b1cfcf0efae07a0d07e0a7b3791d.
I'm also uploading it now to Spigot so please download the update and check if the problem persists.

**Comment by downboy** [comment]
I will download it

**Comment by Vontus** [comment]
Okay! 👍 
Please let me now if it solved the issue, or if it didnt.

**Comment by Vontus** [comment]
Okay I've fixed this. Spigot 1.11 now returns NULL items in crafting recipes instead of an item with type AIR and that was causing the exception.

You can download the latest version from here: https://github.com/Vontus/MagicBottle/releases
